/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ing1.pds.vsc.enterprise;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author aggoun.abdelkrim
 */
public class ReadEnterprise extends javax.swing.JDialog {

    private final String type;
    private String titre;
    private EnterpriseFrame enterpriseFrame;
    private CrudEnterprise crudEnterprise;
    private Enterprise enterprise;
    //
    private boolean activButton;

    /**
     * Creates new form AjouterUser
     *
     * @param parent
     * @param modal
     * @param enterpriseFrame
     * @param enterprise
     * @param type
     */
    public ReadEnterprise(JFrame parent, boolean modal, EnterpriseFrame enterpriseFrame, Enterprise enterprise, String type, CrudEnterprise crudEnterprise) {
        super(parent, modal);
        this.type = type;
        this.crudEnterprise = crudEnterprise;
        this.enterprise = enterprise;
        this.enterpriseFrame = enterpriseFrame;
        initTitre();
        initComponents();
        initDialog();
    }

    private void initDialog() {
        activButton = true;
        buttonAjouter.setEnabled(activButton);

        if (type.equals("add")) {
            enterprise = new Enterprise();
        }
        if (type.equals("upd")) {
            initEnterprise(enterprise);
        }
        this.setLocationRelativeTo(null);
        this.setAlwaysOnTop(true);
        this.setVisible(true);
    }

    private void initTitre() {
        switch (type) {
            case "add":
                titre = "Ajouter une enterprise";
                break;
            case "upd":
                titre = "Modifier une enterprise";
                break;
        }
    }

    private void initEnterprise(Enterprise enterprise) {
        buttonInit.setVisible(false);
        jTextFieldCode.setText(enterprise.getCode());
        jTextFieldLib.setText(enterprise.getLib());
        jTextFieldAdresse.setText(enterprise.getAdresse());
        jTextFieldCodePostal.setText(enterprise.getCodePostal());
        jTextFieldPays.setText(enterprise.getPays());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelButton = new javax.swing.JPanel();
        buttonAjouter = new javax.swing.JButton();
        buttonInit = new javax.swing.JButton();
        buttonFermer = new javax.swing.JButton();
        labelErreur = new javax.swing.JLabel();
        jPanelEnterprise = new javax.swing.JPanel();
        jLabelCode = new javax.swing.JLabel();
        jTextFieldCode = new javax.swing.JTextField();
        jLabelLib = new javax.swing.JLabel();
        jTextFieldLib = new javax.swing.JTextField();
        jLabelAdresse = new javax.swing.JLabel();
        jTextFieldAdresse = new javax.swing.JTextField();
        jTextFieldCodePostal = new javax.swing.JTextField();
        jLabelCodePostal = new javax.swing.JLabel();
        jTextFieldPays = new javax.swing.JTextField();
        jLabelPays = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(titre);
        setResizable(false);

        buttonAjouter.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonAjouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/okBouton.png"))); // NOI18N
        buttonAjouter.setText("Valider");
        buttonAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAjouterActionPerformed(evt);
            }
        });

        buttonInit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonInit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/actualiserBouton.png"))); // NOI18N
        buttonInit.setText("Initialiser");
        buttonInit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInitActionPerformed(evt);
            }
        });

        buttonFermer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonFermer.setForeground(new java.awt.Color(255, 0, 0));
        buttonFermer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/fermeBouton.png"))); // NOI18N
        buttonFermer.setText("Fermer");
        buttonFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFermerActionPerformed(evt);
            }
        });

        labelErreur.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelErreur.setForeground(new java.awt.Color(255, 51, 0));

        javax.swing.GroupLayout panelButtonLayout = new javax.swing.GroupLayout(panelButton);
        panelButton.setLayout(panelButtonLayout);
        panelButtonLayout.setHorizontalGroup(
            panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelButtonLayout.createSequentialGroup()
                        .addGap(0, 390, Short.MAX_VALUE)
                        .addComponent(buttonInit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonAjouter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonFermer))
                    .addComponent(labelErreur, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelButtonLayout.setVerticalGroup(
            panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelErreur, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonFermer)
                    .addComponent(buttonAjouter)
                    .addComponent(buttonInit))
                .addContainerGap())
        );

        jLabelCode.setText("Code *");

        jLabelLib.setText("Libillé *");

        jLabelAdresse.setText("Adresse");

        jLabelCodePostal.setText("Code posal");

        jLabelPays.setText("Pays");

        javax.swing.GroupLayout jPanelEnterpriseLayout = new javax.swing.GroupLayout(jPanelEnterprise);
        jPanelEnterprise.setLayout(jPanelEnterpriseLayout);
        jPanelEnterpriseLayout.setHorizontalGroup(
            jPanelEnterpriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEnterpriseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEnterpriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEnterpriseLayout.createSequentialGroup()
                        .addGroup(jPanelEnterpriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelLib)
                            .addComponent(jLabelCode))
                        .addGap(58, 58, 58)
                        .addGroup(jPanelEnterpriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldLib)
                            .addComponent(jTextFieldCode)))
                    .addGroup(jPanelEnterpriseLayout.createSequentialGroup()
                        .addGroup(jPanelEnterpriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCodePostal)
                            .addComponent(jLabelAdresse))
                        .addGap(28, 28, 28)
                        .addGroup(jPanelEnterpriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldAdresse)
                            .addGroup(jPanelEnterpriseLayout.createSequentialGroup()
                                .addComponent(jTextFieldCodePostal, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(jLabelPays)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldPays)))))
                .addContainerGap())
        );
        jPanelEnterpriseLayout.setVerticalGroup(
            jPanelEnterpriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEnterpriseLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanelEnterpriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCode)
                    .addComponent(jTextFieldCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelEnterpriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLib)
                    .addComponent(jTextFieldLib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelEnterpriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAdresse)
                    .addComponent(jTextFieldAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelEnterpriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodePostal)
                    .addComponent(jTextFieldCodePostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPays)
                    .addComponent(jTextFieldPays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelEnterprise, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanelEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAjouterActionPerformed
        // TODO add your handling code here:
        switch (type) {
            case "add":
                addEnterprise();
                break;
            case "upd":
                updateEnterprise();
                break;
        }
    }//GEN-LAST:event_buttonAjouterActionPerformed

    private void buttonInitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInitActionPerformed
        // TODO add your handling code here:
        initButton();
    }//GEN-LAST:event_buttonInitActionPerformed

    private void buttonFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFermerActionPerformed
        // TODO add your handling code here:
        fermerButton();
    }//GEN-LAST:event_buttonFermerActionPerformed

    private void initButton() {
        buttonAjouter.setEnabled(true);
    }

    private void initEnterprise() {
        enterprise.setCode(jTextFieldCode.getText());
        enterprise.setLib(jTextFieldLib.getText());
        enterprise.setAdresse(jTextFieldAdresse.getText());
        enterprise.setCodePostal(jTextFieldCodePostal.getText());
        enterprise.setPays(jTextFieldPays.getText());
    }

    private boolean verified() {
        if (enterprise.getCode() == null || (enterprise.getCode() != null && enterprise.getCode().isEmpty())) {
            labelErreur.setText("Code est vide");
            return false;
        }
        if (enterprise.getLib() == null || (enterprise.getLib() != null && enterprise.getLib().isEmpty())) {
            labelErreur.setText("Libillé est vide");
            return false;
        }
        if (enterprise.getId() == null) {
            for (Enterprise enter : enterpriseFrame.enterpriseList) {
                if (enter.getCode().equals(enterprise.getCode())) {
                    labelErreur.setText("Code existe déja");
                    return false;
                }
                if (enter.getLib().equals(enterprise.getLib())) {
                    labelErreur.setText("Libillé existe déja");
                    return false;
                }
            }
        } else {
            for (Enterprise enter : enterpriseFrame.enterpriseList) {
                if (enter.getCode().equals(enterprise.getCode()) && !enter.getId().equals(enterprise.getId())) {
                    labelErreur.setText("Code existe déja");
                    return false;
                }
                if (enter.getLib().equals(enterprise.getLib()) && !enter.getId().equals(enterprise.getId())) {
                    labelErreur.setText("Libillé existe déja");
                    return false;
                }
            }
        }
        return true;
    }

    private void addEnterprise() {
        initEnterprise();
        if (verified()) {
            try {
                crudEnterprise.insertEnterprise(enterprise);
                enterpriseFrame.fenetrePricipale.initComboBox();
            } catch (Exception ex) {
                Logger.getLogger(ReadEnterprise.class.getName()).log(Level.SEVERE, null, ex);
            }
            fermerButton();
        }
    }

    private void updateEnterprise() {
        initEnterprise();
        if (verified()) {
            try {
                crudEnterprise.updateEnterprise(enterprise);
                enterpriseFrame.fenetrePricipale.initComboBox();
            } catch (Exception ex) {
                Logger.getLogger(ReadEnterprise.class.getName()).log(Level.SEVERE, null, ex);
            }
            fermerButton();
        }
    }

    private void fermerButton() {
        enterpriseFrame.refrechEnterprise();
        this.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAjouter;
    private javax.swing.JButton buttonFermer;
    private javax.swing.JButton buttonInit;
    private javax.swing.JLabel jLabelAdresse;
    private javax.swing.JLabel jLabelCode;
    private javax.swing.JLabel jLabelCodePostal;
    private javax.swing.JLabel jLabelLib;
    private javax.swing.JLabel jLabelPays;
    private javax.swing.JPanel jPanelEnterprise;
    private javax.swing.JTextField jTextFieldAdresse;
    private javax.swing.JTextField jTextFieldCode;
    private javax.swing.JTextField jTextFieldCodePostal;
    private javax.swing.JTextField jTextFieldLib;
    private javax.swing.JTextField jTextFieldPays;
    private javax.swing.JLabel labelErreur;
    private javax.swing.JPanel panelButton;
    // End of variables declaration//GEN-END:variables
}
