driver: "org.postgresql.Driver"
password: "postgres"
url: "jdbc:postgresql://172.31.249.242:5432/vscdb"
username: "postgres"

create  : "insert into Person (id_person, firstname, age) values (?,?,?)"
delete : "delete from Person where id_person=?"
read : "select * from Person order by id_person"
update : "update Person set firstname=?, age=? where id_person=?"

listenPort: 3344
soTimeout: 2000
ip: 172.31.249.198
