driver: "org.postgresql.Driver"
password: "postgres"
#url: "jdbc:postgresql://172.31.249.242:5432/vscdb"
url: "jdbc:postgresql://localhost:5432/vscdb"
username: "postgres"

listenPort: 3344
soTimeout: 2000
#ip: 172.31.249.246
ip: 127.0.0.1