/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ing1.pds.vsc.local;

import java.awt.Frame;


public class ConsulterLocal extends javax.swing.JDialog {



    public ConsulterLocal(Frame parent, boolean modal, Local local) {
        super(parent, modal);
        initComponents();
        initConsulter(local);
        initDialog();
    }

    private void initDialog() {
        this.setLocationRelativeTo(null);
        this.setAlwaysOnTop(true);
        this.setVisible(true);
    }

    private void initConsulter(Local local) {
        initLocal(local);
    }

    private void initLocal(Local local) {
        jTextFieldNumero.setText(local.getNumero());
        jTextFieldLib.setText(local.getLib());
        jTextFieldBatiment.setText(local.getBatiment());
        jTextFieldEtage.setText(local.getEtage());
        jTextFieldPlace.setText(local.getNbrePlace()+"");
        jTextFieldPlaceOccupe.setText(local.getNbrePlaceOccupe()+"");
        jTextFieldTauxOccupe.setText(local.getTauxOccupation()+"");
        jTextFieldCapteur.setText(local.getNbreCapteur()+"");
        jTextFieldMateriel.setText(local.getNbreMateriel()+"");
        jTextFieldMobilier.setText(local.getNbreMobilier()+"");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelButton = new javax.swing.JPanel();
        buttonFermer = new javax.swing.JButton();
        jPanelEnterprise = new javax.swing.JPanel();
        jLabelNumero = new javax.swing.JLabel();
        jTextFieldNumero = new javax.swing.JTextField();
        jLabelLib = new javax.swing.JLabel();
        jTextFieldLib = new javax.swing.JTextField();
        jTextFieldPlace = new javax.swing.JTextField();
        jLabelPlace = new javax.swing.JLabel();
        jTextFieldPlaceOccupe = new javax.swing.JTextField();
        jLabelPlaceOccupe = new javax.swing.JLabel();
        jLabelBatiment = new javax.swing.JLabel();
        jTextFieldBatiment = new javax.swing.JTextField();
        jTextFieldEtage = new javax.swing.JTextField();
        jLabelEtage = new javax.swing.JLabel();
        jTextFieldTauxOccupe = new javax.swing.JTextField();
        jLabelTauxOccupe = new javax.swing.JLabel();
        jTextFieldCapteur = new javax.swing.JTextField();
        jLabelCapteur = new javax.swing.JLabel();
        jLabelMateriel = new javax.swing.JLabel();
        jTextFieldMateriel = new javax.swing.JTextField();
        jLabelMobilier = new javax.swing.JLabel();
        jTextFieldMobilier = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulter local");
        setResizable(false);

        buttonFermer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonFermer.setForeground(new java.awt.Color(255, 0, 0));
        buttonFermer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/fermeBouton.png"))); // NOI18N
        buttonFermer.setText("Fermer");
        buttonFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFermerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelButtonLayout = new javax.swing.GroupLayout(panelButton);
        panelButton.setLayout(panelButtonLayout);
        panelButtonLayout.setHorizontalGroup(
            panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonLayout.createSequentialGroup()
                .addContainerGap(572, Short.MAX_VALUE)
                .addComponent(buttonFermer)
                .addGap(18, 18, 18))
        );
        panelButtonLayout.setVerticalGroup(
            panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonFermer)
                .addContainerGap())
        );

        jLabelNumero.setText("Numéro");

        jTextFieldNumero.setEnabled(false);

        jLabelLib.setText("Libillé");

        jTextFieldLib.setEnabled(false);

        jTextFieldPlace.setEnabled(false);

        jLabelPlace.setText("Place");

        jTextFieldPlaceOccupe.setEnabled(false);

        jLabelPlaceOccupe.setText("Place occupée");

        jLabelBatiment.setText("Batiment");

        jTextFieldBatiment.setEnabled(false);

        jTextFieldEtage.setEnabled(false);

        jLabelEtage.setText("Etage");

        jTextFieldTauxOccupe.setEnabled(false);

        jLabelTauxOccupe.setText("Place occupée");

        jTextFieldCapteur.setEnabled(false);

        jLabelCapteur.setText("Capteur");

        jLabelMateriel.setText("Materiel");

        jTextFieldMateriel.setEnabled(false);

        jLabelMobilier.setText("Mobilier");

        jTextFieldMobilier.setEnabled(false);

        javax.swing.GroupLayout jPanelEnterpriseLayout = new javax.swing.GroupLayout(jPanelEnterprise);
        jPanelEnterprise.setLayout(jPanelEnterpriseLayout);
        jPanelEnterpriseLayout.setHorizontalGroup(
            jPanelEnterpriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEnterpriseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEnterpriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEnterpriseLayout.createSequentialGroup()
                        .addGroup(jPanelEnterpriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelLib)
                            .addComponent(jLabelNumero)
                            .addComponent(jLabelPlace))
                        .addGap(11, 11, 11)
                        .addGroup(jPanelEnterpriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelEnterpriseLayout.createSequentialGroup()
                                .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelBatiment)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldBatiment, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                                .addComponent(jLabelEtage)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldEtage, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldLib)
                            .addGroup(jPanelEnterpriseLayout.createSequentialGroup()
                                .addGroup(jPanelEnterpriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanelEnterpriseLayout.createSequentialGroup()
                                        .addComponent(jLabelMateriel)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldMateriel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelEnterpriseLayout.createSequentialGroup()
                                        .addComponent(jTextFieldPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(78, 78, 78)
                                        .addComponent(jLabelPlaceOccupe)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldPlaceOccupe, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelTauxOccupe)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldTauxOccupe, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEnterpriseLayout.createSequentialGroup()
                        .addComponent(jLabelCapteur)
                        .addGap(11, 11, 11)
                        .addComponent(jTextFieldCapteur, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelMobilier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldMobilier, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelEnterpriseLayout.setVerticalGroup(
            jPanelEnterpriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEnterpriseLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanelEnterpriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumero)
                    .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBatiment)
                    .addComponent(jTextFieldBatiment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEtage)
                    .addComponent(jTextFieldEtage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelEnterpriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLib)
                    .addComponent(jTextFieldLib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelEnterpriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPlace)
                    .addComponent(jTextFieldPlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPlaceOccupe)
                    .addComponent(jTextFieldPlaceOccupe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTauxOccupe)
                    .addComponent(jTextFieldTauxOccupe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelEnterpriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEnterpriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelCapteur)
                        .addComponent(jTextFieldCapteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldMateriel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelMobilier)
                        .addComponent(jTextFieldMobilier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelMateriel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelEnterprise, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanelEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFermerActionPerformed
        // TODO add your handling code here:
        fermerButton();
    }//GEN-LAST:event_buttonFermerActionPerformed

    private void fermerButton() {
        this.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonFermer;
    private javax.swing.JLabel jLabelBatiment;
    private javax.swing.JLabel jLabelCapteur;
    private javax.swing.JLabel jLabelEtage;
    private javax.swing.JLabel jLabelLib;
    private javax.swing.JLabel jLabelMateriel;
    private javax.swing.JLabel jLabelMobilier;
    private javax.swing.JLabel jLabelNumero;
    private javax.swing.JLabel jLabelPlace;
    private javax.swing.JLabel jLabelPlaceOccupe;
    private javax.swing.JLabel jLabelTauxOccupe;
    private javax.swing.JPanel jPanelEnterprise;
    private javax.swing.JTextField jTextFieldBatiment;
    private javax.swing.JTextField jTextFieldCapteur;
    private javax.swing.JTextField jTextFieldEtage;
    private javax.swing.JTextField jTextFieldLib;
    private javax.swing.JTextField jTextFieldMateriel;
    private javax.swing.JTextField jTextFieldMobilier;
    private javax.swing.JTextField jTextFieldNumero;
    private javax.swing.JTextField jTextFieldPlace;
    private javax.swing.JTextField jTextFieldPlaceOccupe;
    private javax.swing.JTextField jTextFieldTauxOccupe;
    private javax.swing.JPanel panelButton;
    // End of variables declaration//GEN-END:variables
}
