/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ing1.pds.vsc.local;

import edu.ing1.pds.vsc.enterprise.Enterprise;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author aggoun.abdelkrim
 */
public class ReadLocal extends javax.swing.JDialog {

    private final String type;
    private String titre;
    private LocalFrame localFrame;
    private CrudLocal crudLocal;
    private Local local;
    private Enterprise enterprise;
    //
    private boolean activButton;

    /**
     * Creates new form AjouterUser
     *
     * @param parent
     * @param modal
     * @param localFrame
     * @param local
     * @param type
     */
    public ReadLocal(JFrame parent, boolean modal, LocalFrame localFrame, Enterprise enterprise, Local local, String type, CrudLocal crudLocal) {
        super(parent, modal);
        this.type = type;
        this.enterprise = enterprise;
        this.crudLocal = crudLocal;
        this.local = local;
        this.localFrame = localFrame;
        initTitre();
        initComponents();
        initDialog();
    }

    private void initDialog() {
        activButton = true;
        buttonAjouter.setEnabled(activButton);

        if (type.equals("add")) {
            local = new Local();
        }
        if (type.equals("upd")) {
            initLocal(local);
        }
        this.setLocationRelativeTo(null);
        this.setAlwaysOnTop(true);
        this.setVisible(true);
    }

    private void initTitre() {
        switch (type) {
            case "add":
                titre = "Ajouter une local";
                break;
            case "upd":
                titre = "Modifier une local";
                break;
        }
    }

    private void initLocal(Local local) {
        buttonInit.setVisible(false);
        jTextFieldLib.setText(local.getLib());
        jTextFieldBatiment.setText(local.getBatiment());
        jTextFieldEtage.setText(local.getEtage());
        jTextFieldNumero.setText(local.getNumero());
        jTextFieldPlace.setText(local.getNbrePlace() + "");
        jTextFieldPlaceOccupe.setText(local.getNbrePlaceOccupe() + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelButton = new javax.swing.JPanel();
        buttonAjouter = new javax.swing.JButton();
        buttonInit = new javax.swing.JButton();
        buttonFermer = new javax.swing.JButton();
        labelErreur = new javax.swing.JLabel();
        jPanelEnterprise = new javax.swing.JPanel();
        jLabelNumero = new javax.swing.JLabel();
        jTextFieldNumero = new javax.swing.JTextField();
        jLabelLib = new javax.swing.JLabel();
        jTextFieldLib = new javax.swing.JTextField();
        jLabelBatiment = new javax.swing.JLabel();
        jTextFieldBatiment = new javax.swing.JTextField();
        jTextFieldEtage = new javax.swing.JTextField();
        jLabelEtage = new javax.swing.JLabel();
        jTextFieldPlace = new javax.swing.JTextField();
        jTextFieldPlaceOccupe = new javax.swing.JTextField();
        jLabelPlaceOccupe = new javax.swing.JLabel();
        jLabelPlace = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(titre);
        setResizable(false);

        buttonAjouter.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonAjouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/okBouton.png"))); // NOI18N
        buttonAjouter.setText("Valider");
        buttonAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAjouterActionPerformed(evt);
            }
        });

        buttonInit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonInit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/actualiserBouton.png"))); // NOI18N
        buttonInit.setText("Initialiser");
        buttonInit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInitActionPerformed(evt);
            }
        });

        buttonFermer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonFermer.setForeground(new java.awt.Color(255, 0, 0));
        buttonFermer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/fermeBouton.png"))); // NOI18N
        buttonFermer.setText("Fermer");
        buttonFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFermerActionPerformed(evt);
            }
        });

        labelErreur.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelErreur.setForeground(new java.awt.Color(255, 51, 0));

        javax.swing.GroupLayout panelButtonLayout = new javax.swing.GroupLayout(panelButton);
        panelButton.setLayout(panelButtonLayout);
        panelButtonLayout.setHorizontalGroup(
            panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelButtonLayout.createSequentialGroup()
                        .addGap(0, 390, Short.MAX_VALUE)
                        .addComponent(buttonInit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonAjouter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonFermer))
                    .addComponent(labelErreur, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelButtonLayout.setVerticalGroup(
            panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelErreur, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonFermer)
                    .addComponent(buttonAjouter)
                    .addComponent(buttonInit))
                .addContainerGap())
        );

        jLabelNumero.setText("Numéro *");

        jLabelLib.setText("Libillé *");

        jLabelBatiment.setText("Batiment *");

        jLabelEtage.setText("Etage *");

        jTextFieldPlace.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPlaceKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPlaceKeyReleased(evt);
            }
        });

        jTextFieldPlaceOccupe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPlaceOccupeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPlaceOccupeKeyReleased(evt);
            }
        });

        jLabelPlaceOccupe.setText("Place occupée");

        jLabelPlace.setText("Place *");

        javax.swing.GroupLayout jPanelEnterpriseLayout = new javax.swing.GroupLayout(jPanelEnterprise);
        jPanelEnterprise.setLayout(jPanelEnterpriseLayout);
        jPanelEnterpriseLayout.setHorizontalGroup(
            jPanelEnterpriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEnterpriseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEnterpriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEnterpriseLayout.createSequentialGroup()
                        .addGroup(jPanelEnterpriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelLib)
                            .addComponent(jLabelNumero))
                        .addGap(27, 27, 27)
                        .addGroup(jPanelEnterpriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelEnterpriseLayout.createSequentialGroup()
                                .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelBatiment)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldBatiment, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                                .addComponent(jLabelEtage)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldEtage, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldLib)))
                    .addGroup(jPanelEnterpriseLayout.createSequentialGroup()
                        .addComponent(jLabelPlace)
                        .addGap(40, 40, 40)
                        .addComponent(jTextFieldPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelPlaceOccupe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldPlaceOccupe, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)))
                .addContainerGap())
        );
        jPanelEnterpriseLayout.setVerticalGroup(
            jPanelEnterpriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEnterpriseLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanelEnterpriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumero)
                    .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBatiment)
                    .addComponent(jTextFieldBatiment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEtage)
                    .addComponent(jTextFieldEtage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelEnterpriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLib)
                    .addComponent(jTextFieldLib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelEnterpriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPlace)
                    .addComponent(jTextFieldPlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPlaceOccupe)
                    .addComponent(jTextFieldPlaceOccupe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelEnterprise, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanelEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAjouterActionPerformed
        // TODO add your handling code here:
        switch (type) {
            case "add":
                addLocal();
                break;
            case "upd":
                updateLocal();
                break;
        }
    }//GEN-LAST:event_buttonAjouterActionPerformed

    private void buttonInitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInitActionPerformed
        // TODO add your handling code here:
        initButton();
    }//GEN-LAST:event_buttonInitActionPerformed

    private void buttonFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFermerActionPerformed
        // TODO add your handling code here:
        fermerButton();
    }//GEN-LAST:event_buttonFermerActionPerformed

    private void jTextFieldPlaceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPlaceKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            jTextFieldPlace.setEditable(true);
        } else {
            jTextFieldPlace.setEditable(false);
        }
    }//GEN-LAST:event_jTextFieldPlaceKeyPressed

    private void jTextFieldPlaceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPlaceKeyReleased
        // TODO add your handling code here:
        jTextFieldPlace.setEditable(true);
    }//GEN-LAST:event_jTextFieldPlaceKeyReleased

    private void jTextFieldPlaceOccupeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPlaceOccupeKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            jTextFieldPlaceOccupe.setEditable(true);
        } else {
            jTextFieldPlaceOccupe.setEditable(false);
        }
    }//GEN-LAST:event_jTextFieldPlaceOccupeKeyPressed

    private void jTextFieldPlaceOccupeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPlaceOccupeKeyReleased
        // TODO add your handling code here:
        jTextFieldPlaceOccupe.setEditable(true);
    }//GEN-LAST:event_jTextFieldPlaceOccupeKeyReleased

    private void initButton() {
        buttonAjouter.setEnabled(true);
    }

    private void initLocal() {
        local.setLib(jTextFieldLib.getText());
        local.setBatiment(jTextFieldBatiment.getText());
        local.setEtage(jTextFieldEtage.getText());
        local.setNumero(jTextFieldNumero.getText());
        if (jTextFieldPlace.getText().isEmpty()) {
            local.setNbrePlace(0);
        } else {
            local.setNbrePlace(Integer.valueOf(jTextFieldPlace.getText()));
        }
        if (jTextFieldPlaceOccupe.getText().isEmpty()) {
            local.setNbrePlaceOccupe(0);
        } else {
            local.setNbrePlaceOccupe(Integer.valueOf(jTextFieldPlaceOccupe.getText()));
        }
        local.setIdEnterprise(enterprise.getId());
    }

    private boolean verified() {
        if (local.getNumero() == null || (local.getNumero() != null && local.getNumero().isEmpty())) {
            labelErreur.setText("Numéro est vide");
            return false;
        }
        if (local.getBatiment() == null || (local.getBatiment() != null && local.getBatiment().isEmpty())) {
            labelErreur.setText("Batiment est vide");
            return false;
        }
        if (local.getEtage() == null || (local.getEtage() != null && local.getEtage().isEmpty())) {
            labelErreur.setText("Etage est vide");
            return false;
        }
        if (local.getLib() == null || (local.getLib() != null && local.getLib().isEmpty())) {
            labelErreur.setText("Etage est vide");
            return false;
        }
        if (local.getNbrePlace() == null || (local.getNbrePlace() != null && local.getNbrePlace() == 0)) {
            labelErreur.setText("Nombre Place est vide");
            return false;
        }
        if (local.getIdEnterprise() == null) {
            labelErreur.setText("Enterprise est vide");
            return false;
        }
        if (localFrame.localList != null && !localFrame.localList.isEmpty()) {
            if (local.getId() == null) {
                for (Local lcl : localFrame.localList) {
                    if (lcl.getNumero().equals(local.getNumero()) && lcl.getIdEnterprise() == local.getIdEnterprise()) {
                        labelErreur.setText("Numéro existe déja");
                        return false;
                    }
                    if (lcl.getLib().equals(local.getLib()) && lcl.getIdEnterprise() == local.getIdEnterprise()) {
                        labelErreur.setText("Libillé existe déja");
                        return false;
                    }
                }
            } else {
                for (Local lcl : localFrame.localList) {
                    if (lcl.getNumero().equals(local.getNumero()) && !lcl.getId().equals(local.getId()) && lcl.getIdEnterprise() == local.getIdEnterprise()) {
                        labelErreur.setText("Numero existe déja");
                        return false;
                    }
                    if (lcl.getLib().equals(local.getLib()) && !lcl.getId().equals(local.getId()) && lcl.getIdEnterprise() == local.getIdEnterprise()) {
                        labelErreur.setText("Libillé existe déja");
                        return false;
                    }
                }
            }
        }
        if (local.getNbrePlace() < local.getNbrePlaceOccupe()) {
            labelErreur.setText("Nombre de place occupé superieur à nombre de place");
            return false;
        }
        return true;
    }

    private void addLocal() {
        initLocal();
        if (verified()) {
            try {
                crudLocal.insertLocal(local);
            } catch (Exception ex) {
                Logger.getLogger(ReadLocal.class.getName()).log(Level.SEVERE, null, ex);
            }
            fermerButton();
        }
    }

    private void updateLocal() {
        initLocal();
        if (verified()) {
            try {
                crudLocal.updateLocal(local);
            } catch (Exception ex) {
                Logger.getLogger(ReadLocal.class.getName()).log(Level.SEVERE, null, ex);
            }
            fermerButton();
        }
    }

    private void fermerButton() {
        localFrame.refrechLocal();
        this.dispose();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAjouter;
    private javax.swing.JButton buttonFermer;
    private javax.swing.JButton buttonInit;
    private javax.swing.JLabel jLabelBatiment;
    private javax.swing.JLabel jLabelEtage;
    private javax.swing.JLabel jLabelLib;
    private javax.swing.JLabel jLabelNumero;
    private javax.swing.JLabel jLabelPlace;
    private javax.swing.JLabel jLabelPlaceOccupe;
    private javax.swing.JPanel jPanelEnterprise;
    private javax.swing.JTextField jTextFieldBatiment;
    private javax.swing.JTextField jTextFieldEtage;
    private javax.swing.JTextField jTextFieldLib;
    private javax.swing.JTextField jTextFieldNumero;
    private javax.swing.JTextField jTextFieldPlace;
    private javax.swing.JTextField jTextFieldPlaceOccupe;
    private javax.swing.JLabel labelErreur;
    private javax.swing.JPanel panelButton;
    // End of variables declaration//GEN-END:variables
}
